version: '3.8'

services:
  identity-api:
    image: ${DOCKER_REGISTRY-}richillcapitalidentityapi
    container_name: identity-api 
    
    build:
      context: .
      dockerfile: Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql

    ports:
      - 1433:1433
    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong_Password    