@HostAddress = http://127.0.0.1:80

### Create bot.
POST {{HostAddress}}/api/bots
Accept: application/json
Content-Type: application/json

{
  "botId": "123",
  "name": "asds",
  "description": "asdaab",
  "tradingPlatform": "xq"
}

### Get bot by id
GET {{HostAddress}}/api/bots/123
Accept: application/json
Content-Type: application/json

{

}

### List all bots
GET {{HostAddress}}/api/bots
Accept: application/json
Content-Type: application/json


### Delete bot
DELETE {{HostAddress}}/api/bots/123
Accept: application/json
Content-Type: application/json

{

}